name: todos_flutter_bloc_demo
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  flutter_bloc: ^8.0.1 # state management purpose
  uuid: ^3.0.6 # unique id provider
  equatable: ^2.0.3 # enforces value equality
  json_annotation: ^4.5.0 # provides annotations for (de)serialization
  shared_preferences: ^2.0.15
  rxdart: ^0.27.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1
  build_runner: ^2.1.11
  json_serializable: ^6.2.0

flutter:
  uses-material-design: true
